[package]
name = "mini-revm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evm = "0.37.0"
hex = "0.4"
num-bigint = "0.4"
primitive-types = "0.12.1"